"""create initial tables

Revision ID: 3a723fbf555c
Revises: 
Create Date: 2025-11-19 17:11:46.507953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a723fbf555c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id_cargo', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_cargo')
    )
    op.create_table('categoria',
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descuento_categoria', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('id_categoria', 'nombre', name='Categoria_UQ'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_venta',
    sa.Column('id_estado_venta', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_estado_venta'),
    sa.UniqueConstraint('id_estado_venta', 'nombre', name='EstadoVenta_UQ')
    )
    op.create_table('formato_reporte',
    sa.Column('id_formato_reporte', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_formato_reporte'),
    sa.UniqueConstraint('id_formato_reporte', 'nombre', name='FormatoReporte_UQ'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('id_rol', 'nombre', name='Rol_UQ'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('descuento_producto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('id_producto', 'nombre', name='Producto_UQ'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('reporte',
    sa.Column('id_reporte', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('formato_archivo', sa.String(length=10), nullable=False),
    sa.Column('periodo_persistencia', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('formato_reporte_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['formato_reporte_id'], ['formato_reporte.id_formato_reporte'], ),
    sa.PrimaryKeyConstraint('id_reporte'),
    sa.UniqueConstraint('id_reporte', 'nombre', name='Reporte_UQ'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('url')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rol_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('length(dni) >= 8', name='dni_min_len'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('rol_reporte',
    sa.Column('reporte_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('asignado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reporte_id'], ['reporte.id_reporte'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('reporte_id', 'rol_id')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.UUID(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('estado_venta_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['estado_venta_id'], ['estado_venta.id_estado_venta'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('comprobante',
    sa.Column('id_comprobante', sa.UUID(), nullable=False),
    sa.Column('venta_id', sa.UUID(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('fecha_venta', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lugar_venta', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_comprobante'),
    sa.UniqueConstraint('id_comprobante', 'venta_id', name='Comprobante_UQ')
    )
    op.create_table('comprobante_cargo',
    sa.Column('comprobante_id', sa.UUID(), nullable=False),
    sa.Column('cargo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id_cargo'], ),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id_comprobante'], ),
    sa.PrimaryKeyConstraint('comprobante_id', 'cargo_id')
    )
    op.create_table('comprobante_producto',
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('comprobante_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id_comprobante'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('producto_id', 'comprobante_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprobante_producto')
    op.drop_table('comprobante_cargo')
    op.drop_table('comprobante')
    op.drop_table('venta')
    op.drop_table('rol_reporte')
    op.drop_table('usuario')
    op.drop_table('reporte')
    op.drop_table('producto')
    op.drop_table('rol')
    op.drop_table('formato_reporte')
    op.drop_table('estado_venta')
    op.drop_table('categoria')
    op.drop_table('cargo')
    # ### end Alembic commands ###
