"""add_ONCASCADE_elimination_parameter

Revision ID: d196ad80f72f
Revises: 3a723fbf555c
Create Date: 2025-11-26 22:24:20.710776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd196ad80f72f'
down_revision: Union[str, Sequence[str], None] = '3a723fbf555c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comprobante_venta_id_fkey'), 'comprobante', type_='foreignkey')
    op.create_foreign_key(None, 'comprobante', 'venta', ['venta_id'], ['id_venta'], ondelete='CASCADE')
    op.drop_constraint(op.f('comprobante_cargo_comprobante_id_fkey'), 'comprobante_cargo', type_='foreignkey')
    op.drop_constraint(op.f('comprobante_cargo_cargo_id_fkey'), 'comprobante_cargo', type_='foreignkey')
    op.create_foreign_key(None, 'comprobante_cargo', 'cargo', ['cargo_id'], ['id_cargo'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comprobante_cargo', 'comprobante', ['comprobante_id'], ['id_comprobante'], ondelete='CASCADE')
    op.drop_constraint(op.f('comprobante_producto_producto_id_fkey'), 'comprobante_producto', type_='foreignkey')
    op.drop_constraint(op.f('comprobante_producto_comprobante_id_fkey'), 'comprobante_producto', type_='foreignkey')
    op.create_foreign_key(None, 'comprobante_producto', 'producto', ['producto_id'], ['id_producto'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comprobante_producto', 'comprobante', ['comprobante_id'], ['id_comprobante'], ondelete='CASCADE')
    op.alter_column('producto', 'categoria_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('producto_categoria_id_fkey'), 'producto', type_='foreignkey')
    op.create_foreign_key(None, 'producto', 'categoria', ['categoria_id'], ['id_categoria'], ondelete='SET NULL')
    op.drop_constraint(op.f('rol_reporte_reporte_id_fkey'), 'rol_reporte', type_='foreignkey')
    op.drop_constraint(op.f('rol_reporte_rol_id_fkey'), 'rol_reporte', type_='foreignkey')
    op.create_foreign_key(None, 'rol_reporte', 'rol', ['rol_id'], ['id_rol'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rol_reporte', 'reporte', ['reporte_id'], ['id_reporte'], ondelete='CASCADE')
    op.drop_constraint(op.f('venta_usuario_id_fkey'), 'venta', type_='foreignkey')
    op.create_foreign_key(None, 'venta', 'usuario', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venta', type_='foreignkey')
    op.create_foreign_key(op.f('venta_usuario_id_fkey'), 'venta', 'usuario', ['usuario_id'], ['id_usuario'])
    op.drop_constraint(None, 'rol_reporte', type_='foreignkey')
    op.drop_constraint(None, 'rol_reporte', type_='foreignkey')
    op.create_foreign_key(op.f('rol_reporte_rol_id_fkey'), 'rol_reporte', 'rol', ['rol_id'], ['id_rol'])
    op.create_foreign_key(op.f('rol_reporte_reporte_id_fkey'), 'rol_reporte', 'reporte', ['reporte_id'], ['id_reporte'])
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.create_foreign_key(op.f('producto_categoria_id_fkey'), 'producto', 'categoria', ['categoria_id'], ['id_categoria'])
    op.alter_column('producto', 'categoria_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'comprobante_producto', type_='foreignkey')
    op.drop_constraint(None, 'comprobante_producto', type_='foreignkey')
    op.create_foreign_key(op.f('comprobante_producto_comprobante_id_fkey'), 'comprobante_producto', 'comprobante', ['comprobante_id'], ['id_comprobante'])
    op.create_foreign_key(op.f('comprobante_producto_producto_id_fkey'), 'comprobante_producto', 'producto', ['producto_id'], ['id_producto'])
    op.drop_constraint(None, 'comprobante_cargo', type_='foreignkey')
    op.drop_constraint(None, 'comprobante_cargo', type_='foreignkey')
    op.create_foreign_key(op.f('comprobante_cargo_cargo_id_fkey'), 'comprobante_cargo', 'cargo', ['cargo_id'], ['id_cargo'])
    op.create_foreign_key(op.f('comprobante_cargo_comprobante_id_fkey'), 'comprobante_cargo', 'comprobante', ['comprobante_id'], ['id_comprobante'])
    op.drop_constraint(None, 'comprobante', type_='foreignkey')
    op.create_foreign_key(op.f('comprobante_venta_id_fkey'), 'comprobante', 'venta', ['venta_id'], ['id_venta'])
    # ### end Alembic commands ###
